default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: deploy_app_development
  username: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: deploy_app_test

production:
  <<: *default
  database: deploy_app_prod
  username: postgres
  host: localhost
  port: 5432
  # password: <%= ENV["DEPLOY_APP_DATABASE_PASSWORD"] %>
  # url: <%= ENV["MY_APP_DATABASE_URL"] %>
